# -*- coding: utf-8 -*-
"""DiceGame - My Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBUM3d6fFiHdzFcARLTGF_rF2ACfO6aT
"""

import random

rolls = []
point_1 = 0
point_2 = 0
total = 0
counter = 1

p1_name = str(input("Insert a name for player one: "))
p2_name = str(input("Insert a name for player two: "))
rounds = int(input("How many rounds do you want to play? "))

#n = int(input("How many sides are on the die you want to use? "))
def roll (total):
    for i in range(0, 2):
        rolls.append(random.randint(1, 6))

    total = sum(rolls)
    return total

def game (point_1, point_2):
    point_1 = point_1 + roll(total)
    rolls.clear()

    point_2 = point_2 + roll(total)
    rolls.clear()

    return point_1, point_2


def add_subtract (point_1, point_2):
    if point_1 % 2 == 0:
        point_1 = point_1 + 10
    else:
        point_1 = point_1 - 5

    if point_2 % 2 == 0:
        point_2 = point_2 + 10
    else:
        point_2 = point_2 - 5

    return point_1, point_2


while counter <= rounds:
    point_1, point_2 = game(point_1, point_2)
    point_1, point_2 = add_subtract(point_1, point_2)
    print ("\n", p1_name, "has", point_1, "points after round", counter)
    print ("\n", p2_name, "has", point_2, "points after round", counter)

    counter += 1

if point_1 == point_2:
    break_1 = random.randint(1, 6)
    break_2 = random.randint(1, 6)
    if break_1 > break_2:
        print ("\n----------------------------------------------------")
        print ("\n", p1_name, "is the winner with", point_1, " points!")
    elif break_2 > break_1:
        print ("\n----------------------------------------------------")
        print ("\n", p2_name, "is the winner with", point_2, " points!")
    else:
        print ("\n----------------------------------------------------")
        print ("\nTie breaker tied, everyone loses :[")
elif point_1 > point_2:
    print ("\n----------------------------------------------------")
    print ("\n", p1_name, "is the winner with", point_1, "points!")
else:
    print ("\n----------------------------------------------------")
    print ("\n", p2_name, "is the winner with", point_2, "points!")